/* ============================================================
   Regenerates assets/js/world-map-data.js — the shape of the world.

   You almost certainly never need to run this. The generated file is
   committed, and changing WHICH countries light up is done by editing the
   list in index.html (#friendmap), not here. This exists so the geometry
   isn't an unexplained blob: run it if you ever want a different
   projection, a finer resolution, or more of the small island states.

     cd tools
     npm install d3-geo@3 topojson-client@3 world-atlas@2
     node gen-map.mjs

   Country outlines: Natural Earth 110m via the world-atlas package.
   Natural Earth data is in the public domain.
   ============================================================ */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import * as topojson from "topojson-client";
import * as d3 from "d3-geo";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

const topo = JSON.parse(readFileSync(here("node_modules/world-atlas/countries-110m.json"), "utf8"));
const geo = topojson.feature(topo, topo.objects.countries);

// Drop Antarctica: it eats a third of the frame and nobody lives there.
geo.features = geo.features.filter((f) => f.properties.name !== "Antarctica");

const W = 1000;
const projection = d3.geoNaturalEarth1().fitWidth(W, geo);
const bounds = d3.geoPath(projection).bounds(geo);
const H = Math.ceil(bounds[1][1] - bounds[0][1]);
const [tx, ty] = projection.translate();
projection.translate([tx, ty - bounds[0][1]]); // trim the empty band up top

const path = d3.geoPath(projection);
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(parseFloat(n) * 10) / 10));

const countries = geo.features
  .map((f) => ({ n: f.properties.name, d: round(path(f) || "") }))
  .filter((c) => c.d)
  .sort((a, b) => a.n.localeCompare(b.n));

// At 110m the very small states have no outline at all, so they get a dot
// instead. [name, latitude, longitude]
const smallStates = [
  ["Singapore", 1.35, 103.82], ["Malta", 35.9, 14.5], ["Bahrain", 26.07, 50.55],
  ["Maldives", 3.2, 73.22], ["Mauritius", -20.3, 57.55], ["Seychelles", -4.62, 55.45],
  ["Comoros", -11.7, 43.26], ["Cabo Verde", 15.12, -23.6], ["São Tomé and Príncipe", 0.34, 6.73],
  ["Andorra", 42.51, 1.52], ["Monaco", 43.73, 7.42], ["Liechtenstein", 47.14, 9.55],
  ["San Marino", 43.94, 12.45], ["Vatican City", 41.9, 12.45], ["Hong Kong", 22.32, 114.17],
  ["Macau", 22.2, 113.55], ["Barbados", 13.19, -59.54], ["Saint Lucia", 13.9, -60.98],
  ["Grenada", 12.11, -61.68], ["Antigua and Barbuda", 17.11, -61.85],
  ["Saint Kitts and Nevis", 17.34, -62.76], ["Saint Vincent and the Grenadines", 13.25, -61.2],
  ["Dominica", 15.41, -61.37], ["Samoa", -13.76, -172.1], ["Tonga", -21.18, -175.2],
  ["Kiribati", 1.33, 172.98], ["Marshall Islands", 7.12, 171.19],
  ["Micronesia", 6.92, 158.16], ["Palau", 7.5, 134.62], ["Nauru", -0.53, 166.92],
  ["Tuvalu", -8.52, 179.19],
];

const points = smallStates.map(([n, lat, lon]) => {
  const [x, y] = projection([lon, lat]);
  return { n, x: Math.round(x * 10) / 10, y: Math.round(y * 10) / 10 };
});

const header = `/* ============================================================
   Friend map geometry — generated by tools/gen-map.mjs, not hand-edited.

   Country outlines from Natural Earth 110m (public domain), projected with
   Natural Earth I and rounded to keep the file small. States too small to
   have an outline at this resolution are listed as points and drawn as dots.

   To change WHICH countries are highlighted, don't touch this file — edit
   the list in index.html (#friendmap). This is only the shape of the world.
   ============================================================ */
`;

const body = "window.WORLD_MAP = " + JSON.stringify({ width: W, height: H, countries, points }) + ";\n";

writeFileSync(here("../assets/js/world-map-data.js"), header + body);
console.log(`wrote assets/js/world-map-data.js — viewBox 0 0 ${W} ${H}, ${countries.length} countries, ${points.length} dots`);
